language: python
  
python: "3.6"

git:
  depth: 1
  
install:
  - pip install -r requirements.txt
  - pip install codecov
  
script:
  - python -m discover -p "test_*.py"

script:
  - coverage run manage.py test BetterTogether/tests

after_success:
  - codecov
  