language: python
    python:
      - "3.6"
      - "3.7"
    services:
      - mysql
    env:
      - DJANGO=2.2.5 
      - DB=mysql
    install:
      - pip install django==$DJANGO --quiet
    before_script:
      - mysql -e 'create database test;' -u root
    script:
      - python manage.py test