# Generated by Django 2.2.5 on 2019-11-06 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender (F or M)')),
                ('age', models.IntegerField(max_length=2, verbose_name='Age')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='', verbose_name='Location')),
                ('destination', models.TextField(default='', verbose_name='Destination')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('host', models.CharField(default='', max_length=30, verbose_name="Host's Name")),
                ('participants', models.ManyToManyField(to='BetterTogetherApp.Info')),
            ],
        ),
        migrations.CreateModel(
            name='SharePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='', verbose_name='Location')),
                ('brand', models.TextField(default='', verbose_name='Brand')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('host', models.CharField(default='', max_length=30, verbose_name="Host's Name")),
                ('participants', models.ManyToManyField(to='BetterTogetherApp.Info')),
            ],
        ),
        migrations.CreateModel(
            name='ShareFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='', verbose_name='Location')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('host', models.CharField(default='', max_length=30, verbose_name="Host's Name")),
                ('participants', models.ManyToManyField(to='BetterTogetherApp.Info')),
            ],
        ),
    ]
