# Generated by Django 2.2.5 on 2019-11-25 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('BetterTogetherApp', '0001_initial'), ('BetterTogetherApp', '0002_auto_20191107_1857'), ('BetterTogetherApp', '0003_auto_20191107_1920'), ('BetterTogetherApp', '0004_auto_20191107_1922'), ('BetterTogetherApp', '0005_auto_20191111_0638'), ('BetterTogetherApp', '0006_auto_20191122_1745'), ('BetterTogetherApp', '0007_auto_20191122_1748'), ('BetterTogetherApp', '0008_auto_20191122_2120'), ('BetterTogetherApp', '0009_auto_20191122_2130'), ('BetterTogetherApp', '0010_auto_20191122_2153'), ('BetterTogetherApp', '0011_auto_20191122_2157')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='', verbose_name='Location')),
                ('brand', models.TextField(default='', verbose_name='Brand')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('host', models.CharField(default='', max_length=30, verbose_name="Host's Name")),
                ('participants', models.ManyToManyField(to='BetterTogetherApp.Info')),
                ('num_people', models.IntegerField(default=2, verbose_name='Number of people')),
                ('full', models.BooleanField(default=False)),
                ('location_name', models.TextField(default='', verbose_name='Location Name')),
            ],
        ),
        migrations.CreateModel(
            name='ShareFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='', verbose_name='Location')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
                ('host', models.CharField(default='', max_length=30, verbose_name="Host's Name")),
                ('participants', models.ManyToManyField(to='BetterTogetherApp.Info')),
                ('num_people', models.IntegerField(default=2, verbose_name='Number of people')),
                ('full', models.BooleanField(default=False)),
                ('location_name', models.TextField(default='', verbose_name='Location Name')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender (F or M)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brief_info', models.TextField(default='', verbose_name='Background Infomation')),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='', verbose_name='Location')),
                ('destination', models.TextField(default='', verbose_name='Destination')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('date_time', models.DateTimeField(default='2019-11-22 21:57:35', verbose_name='Date and Time')),
                ('host', models.CharField(default='', max_length=30, verbose_name="Host's Name")),
                ('participants', models.ManyToManyField(to='BetterTogetherApp.Info')),
                ('num_people', models.IntegerField(default=2, verbose_name='Number of people')),
                ('full', models.BooleanField(default=False)),
                ('destination_name', models.TextField(default='', verbose_name='Destination Name')),
                ('location_name', models.TextField(default='', verbose_name='Location Name')),
            ],
        ),
    ]
