# Generated by Django 2.2.5 on 2019-11-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='twitter',
            field=models.TextField(default='', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-28 14:25:20', verbose_name='Date and Time'),
        ),
    ]
