# Generated by Django 2.2.5 on 2019-11-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefood',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharefood',
            name='num_people',
            field=models.IntegerField(default=2, verbose_name='Number of people'),
        ),
        migrations.AddField(
            model_name='sharepromotion',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharepromotion',
            name='num_people',
            field=models.IntegerField(default=2, verbose_name='Number of people'),
        ),
        migrations.AddField(
            model_name='shareride',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shareride',
            name='num_people',
            field=models.IntegerField(default=2, verbose_name='Number of people'),
        ),
    ]
