# Generated by Django 3.1 on 2019-11-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-29 14:01:04', verbose_name='Date and Time'),
        ),
    ]
