# Generated by Django 2.2.5 on 2019-12-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharefood',
            name='host_number',
            field=models.CharField(default='', max_length=10, verbose_name="Host's Phone Number"),
        ),
        migrations.AddField(
            model_name='sharepromotion',
            name='host_number',
            field=models.CharField(default='', max_length=10, verbose_name="Host's Phone Number"),
        ),
        migrations.AddField(
            model_name='shareride',
            name='host_number',
            field=models.CharField(default='', max_length=10, verbose_name="Host's Phone Number"),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-12-14 12:29:15', verbose_name='Date and Time'),
        ),
    ]
