# Generated by Django 2.2.5 on 2019-11-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0002_auto_20191127_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-27 16:15:46', verbose_name='Date and Time'),
        ),
    ]
