# Generated by Django 2.2.5 on 2019-12-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0002_auto_20191213_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-12-13 15:11:48', verbose_name='Date and Time'),
        ),
    ]
