# Generated by Django 2.2.5 on 2019-12-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0002_auto_20191214_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-12-14 01:35:19', verbose_name='Date and Time'),
        ),
    ]
