# Generated by Django 2.2.5 on 2019-12-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0002_auto_20191129_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='twitter',
            field=models.TextField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-12-04 16:34:01', verbose_name='Date and Time'),
        ),
    ]
