# Generated by Django 2.2.5 on 2019-11-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0003_auto_20191127_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-27 17:44:14', verbose_name='Date and Time'),
        ),
    ]
