# Generated by Django 2.2.5 on 2019-12-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0003_auto_20191214_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-12-14 16:25:39', verbose_name='Date and Time'),
        ),
    ]
