# Generated by Django 2.2.5 on 2019-11-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0003_auto_20191107_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharefood',
            name='vacant',
        ),
        migrations.RemoveField(
            model_name='sharepromotion',
            name='vacant',
        ),
        migrations.RemoveField(
            model_name='shareride',
            name='vacant',
        ),
        migrations.AddField(
            model_name='sharefood',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharepromotion',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shareride',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
