# Generated by Django 2.2.5 on 2019-11-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0004_auto_20191107_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='brief_info',
            field=models.TextField(default='', verbose_name='Background Infomation'),
        ),
        migrations.AddField(
            model_name='sharefood',
            name='location_name',
            field=models.TextField(default='', verbose_name='Location Name'),
        ),
        migrations.AddField(
            model_name='sharepromotion',
            name='location_name',
            field=models.TextField(default='', verbose_name='Location Name'),
        ),
        migrations.AddField(
            model_name='shareride',
            name='destination_name',
            field=models.TextField(default='', verbose_name='Destination Name'),
        ),
        migrations.AddField(
            model_name='shareride',
            name='location_name',
            field=models.TextField(default='', verbose_name='Location Name'),
        ),
    ]
