# Generated by Django 2.2.5 on 2019-12-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0003_auto_20191214_0135'),
        ('BetterTogetherApp', '0004_auto_20191215_1227'),
    ]

    operations = [
    ]
