# Generated by Django 2.2.5 on 2019-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0004_auto_20191127_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-27 19:18:05', verbose_name='Date and Time'),
        ),
    ]
