# Generated by Django 2.2.5 on 2019-11-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0005_auto_20191111_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='sharefood',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-22 17:45:40', verbose_name='Date and Time'),
        ),
    ]
