# Generated by Django 2.2.5 on 2019-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0006_auto_20191127_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-27 20:03:11', verbose_name='Date and Time'),
        ),
    ]
