# Generated by Django 2.2.5 on 2019-11-22 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0006_auto_20191122_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-22 17:48:25', verbose_name='Date and Time'),
        ),
    ]
