# Generated by Django 2.2.5 on 2019-12-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0007_auto_20191215_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='brief_info',
            field=models.TextField(default='NOT SET', verbose_name='Background Infomation'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_num',
            field=models.CharField(default='NOT SET', max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='sharefood',
            name='date_time',
            field=models.TextField(default='2019-12-15 14:47:20', verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='sharepromotion',
            name='date_time',
            field=models.TextField(default='2019-12-15 14:47:20', verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.TextField(default='2019-12-15 14:47:20', verbose_name='Date and Time'),
        ),
    ]
