# Generated by Django 2.2.5 on 2019-11-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0008_auto_20191122_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='age',
        ),
        migrations.AddField(
            model_name='info',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-22 21:30:06', verbose_name='Date and Time'),
        ),
    ]
