# Generated by Django 2.2.5 on 2019-12-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0009_auto_20191215_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='twitter',
            field=models.TextField(default='NOT SET', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='sharefood',
            name='date_time',
            field=models.TextField(default='2019-12-15 18:01:58', verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='sharepromotion',
            name='date_time',
            field=models.TextField(default='2019-12-15 18:01:58', verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.TextField(default='2019-12-15 18:01:58', verbose_name='Date and Time'),
        ),
    ]
