# Generated by Django 2.2.5 on 2019-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterTogetherApp', '0010_auto_20191122_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareride',
            name='date_time',
            field=models.DateTimeField(default='2019-11-22 21:57:35', verbose_name='Date and Time'),
        ),
    ]
